<?xml version="1.0"?>

<package format="3">

  <name>panda_pick_place</name>

  <version>0.0.0</version>

  <description>
    Panda MoveIt2 pick and place study package
  </description>

  <maintainer email="rrc@example.com">
    rrc
  </maintainer>

  <license>Apache-2.0</license>


  <buildtool_depend>
    ament_cmake
  </buildtool_depend>


  <depend>rclcpp</depend>

  <depend>
    moveit_ros_planning_interface
  </depend>

  <depend>
    moveit_msgs
  </depend>

  <depend>
    shape_msgs
  </depend>

  <depend>
    geometry_msgs
  </depend>


  <export>

    <build_type>
      ament_cmake
    </build_type>

  </export>

</package>
